### ISSUE TITLE
Configurar repositório do github

### ISSUE THREAD

**Issue by ecureuill** [ecureuill/ADA_1042_AQ1_SB_CartaoService#40]

**Comment by ecureuill** [comment]
Um **monorepositório** é um repositorio (ou seja, um conjunto de arquivos) no Git que contém todos os código-fonte de uma determinada aplicação ou projeto. Isso significa que todo o código-fonte está em um único repositório, facilitando a organização e gerenciamento do código.

Já um **multirepositório** é um modelo de desenvolvimento que utiliza múltiplos repositories no Git para armazenar diferentes partes do código-fonte de um projeto. Cada repository (ou sub-repositório) contém apenas uma parte do código-fonte, permitindo que as equipes de desenvolvimento trabalhem em diferentes áreas do projeto de forma independente uns dos outros.

Existem vantagens e desvantagens em utilizar um monorepositório ou um multirepositório. 

Algumas das principais vantagens do monorepositório incluem:

* Maior facilidade de organização e gerenciamento do código;
* Menos conflitos de merge, pois todas as alterações são feitas em um único repositório;
* Melhor suporte para o uso de ferramentas de análise de código e scanning de vulnerabilidades, já que todo o código está em um único lugar.
 
Já algumas das principais vantagens do multirepositório incluem:

* Mayor flexibilidade e escalabilidade, pois cada equipe pode trabalhar em diferentes áreas do projeto sem interferir uns com os outros;
* Maior segurança, pois cada repository pode ter suas próprias politicas de acesso e controle de versão;
* Maior capacidade de reutilizar código, pois cada repository pode ser reuseado em diferentes proyectos.
 
No entanto, também existem **desvantagens** em usar um monorepositório ou um multirepositório. Por exemplo, um monorepositório pode se tornar grande e complexo demais, tornando difícil a gestão eorganização do código. Já um multirepositório pode requerer mais esforço para gestionar as dependências entre os diferentes repositories.

Em resumo, a escolha entre um monorepositório ou um multirepositório depende das necessidades específicas do projeto e da equipe de desenvolvimento. É importante avaliar cuidadosamente as vantagens e desvantagens de cada abordagem antes de tomar uma decisão.

Fonte: llama2

Ou um artigo da alura

https://www.alura.com.br/artigos/monorepo-usa-lo-desenvolver-integrar-grandes-projetos


@leofss @gmessiasc @thiago-granja @brunaminusso

**Comment by ecureuill** [comment]
Passos

1. Criar os repositórios independentes
1. Clone na sua máquina o repositório principal
    `git clone URL_DO_REPOSITORIO_PRINCIPAL.git`
1. Navegue até o repositório central e adicione cada repositório como um módulo
    ```bash
    cd NOME_DO_PROJETO
    git submodule add URL_DO_REPOSITORIO.git
    ```
1. `git commit -m 'added submodule'`
1. `git push`

![image](https://github.com/ecureuill/ADA_1042_AQ1_SB_CartaoService/assets/993369/107f0b14-f8e8-4882-b395-bc0c8eeb23f9)

https://www.atlassian.com/git/tutorials/git-submodule

**Comment by ecureuill** [comment]
@gmessiasc nessa situação não precisa configurar um projeto com graddle, pq cada repositório terá o seu projeto independente. 

Depois a gente cria um docker compose para subir todos os serviços de uma vez

**Comment by ThusSpokeBieu** [comment]
> @gmessiasc nessa situação não precisa configurar um projeto com graddle, pq cada repositório terá o seu projeto independente.
> 
> Depois a gente cria um docker compose para subir todos os serviços de uma vez

Podemos ter essa abordagem sem problemas!! 

A ideia de usar o gradle para gerenciar os módulos dos microsserviços tem algumas vantagens, como:
- Podemos ter a reutilização de classlibs, como um serviço para o domínio encapsulado que fornece recursos para todos os ms de um ponto só. 
- Ter um módulo de testes que abrange todos os microsserviços para permitir testes de integração específicos. 

De qualquer forma, também tem desvantagens. Já que precisaria, por exemplo, de uma coordenação maior e mais dependência entre equipes durante o desenvolvimento.

Para manter a independência, podemos seguir sem os submodulos do gradle, mantendo apenas os do github.

**Comment by ThusSpokeBieu** [comment]
@ecureuill se possível, libera nois como mantainers nos submodulos tbb

**Comment by ThusSpokeBieu** [comment]
Para clonar todos os submodulos (você pode clonar apenas o repositório que você vai trabalhar também):

``` bash
# clona o repositório
git clone git@github.com:ecureuill/ADA_1042_AQ1_SB_CartaoService.git

# muda a branch para onde estão os microserviços:
git checkout ms-central

# inicializa os submodulos
git submodule init

# atualiza os submodulos
git submodule update
```

Para verificar se funcionou, acesse seu repositório e use os comandos: 

```
# verifica se as branchs são do monorepo ou do modulo 
git branch
```
